language: go
sudo: false
matrix:
  include:
  - go: 1.13.x
before_install:
- 
install:
- 
script:
- diff -u <(echo -n) <(gofmt -d .)
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
- go build -o go-dotenv-generator cmd/godotenvgenerator/cmd.go
deploy:
  provider: releases
  api_key:
    secure: C2zRWyyTKFjPTGHCnPQ5g8Zjon+CC8q+nqBf8v2e3CNGc0RG4XqJArXaQ14hF0HPAdSY5JqhUNAupie7z8BwLuUQiqo7fPckSFKG5Sx94Zc7GAmoGUsQbzSYjSu5QeP2YFD/QJYfKRSkdhUbF8oea1Nev1BuUaBj+bQX+onrPms7Xbp+Q1WgbhBsKSiA+FDBfPiKwcMaT4RFnPtBOTLGGBW80+EMr5CngVlktV2fQ1evBZzEORkLldTDduX0/9i7UAp5WEWEemR5lV1XIZpeYtnYubXn9N9WwG51v/h0K2vZSpenncZNFr3h3vfA8PODFiek89mMcNmixGlLtTInDfyt8awxUSnLoPFFi1QMEZA17GaMWW+6xFkOP698ptd0BP/pJ2m/RddSJs5u9hJyrfzRcYWSXKewafM5OeCf+b/3p1kO7x5ugjoGu8tXfU2ZEYtR3k1pCEXbaKm2EenD2U2+/2Qw2vxDGa/x/9hycCSUPZIFCO7kFiV6wA4FrxTlK+W99wz/315DYzLfJfDvDu1/MyKnl6AdsJnV5b24NT4jskfIAayWsNOxFeokteGYFmaOfYyrvvxH54AENjpYJOxkGjfovE224Olj6HEJ/gz+GpDBsYcMDdxojfLYeozzKeidyydAbwJaaiUSfx5MFo6xncwUzjT0Val2ES5zfBE=
  file: go-dotenv-generator
  on:
    repo: czhujer/go-dotenv-generator
    tags: true
