language: go
sudo: false
matrix:
  include:
  - go: 1.13.x
before_install:
- 
install:
- 
script:
- diff -u <(echo -n) <(gofmt -d .)
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
- go build -o go-dotenv-generator cmd/godotenvgenerator/cmd.go
deploy:
  provider: releases
  api_key:
    secure: Ghq1jUwSfMJAY1O7mCOeydIZMZXxjECtqClbmyQWk3DntMZnbbwCUBwPU9ozhnU6P2it+gnOUXhAjgIW8QkPTS9F4eV6kT3r4NztuHTTJm4jhhHn4suKlqPm/WZfl522CH8LoE/9Z3S34GEigtwCPurvlLcnH0ByRDMwDSow/dEJ4akPYxQ5MfRaN32IsePFhryWqlYJa6qfKlkZZ611i+W4UP4Ga2y5lxgY3SG+8uHIv9rk99gCZ/xt3Id6r5M5AzjMAw5PM+rDHIdudqv05Yk4DzTouEp3OC2KY/q4IR7u1Wy1+XBrAvQbSBG9bP32GQzw6JzobUF5WEP7/i58gEmdFFyacqNfbsqwZ8DsZlUbGU6Vrt78IKGI3mBK2BSYi4HL7DkCVkVVLMczcoMG2p7AyKu3EHQpv09pkvLw1OqWcYlUBSTjihlXCwDzGciczvCLAJiheWHhh38uQypIyJxwB9bS6LUs4ZpQ0ZXVeRLFVUaP+GutJFRNzOtGfPIoNvnyCuQgmAaM0DirRvu9LMgxuUbwWKidPINLB3q4jMyEXH2dA6cv77DGQODeXF6IFYXTQYXgQYsd4iTnUJV2qKIrwtu0R2cNQMOnVwWAA7QuuhOH4kp5cNHW8s9rbyi3Z5gRgK1lgdWbLeMk0fu+X3LUD1oecHB45Si8MB+fsZU=
  file: go-dotenv-generator
  on:
    repo: czhujer/go-dotenv-generator
    tags: true
